"""
Django settings for church_site project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config

import os



ENV = config("ENV", default="local")
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

LOGIN_URL = '/login/' # Redireciona para a página de login se não estiver autenticado
LOGIN_REDIRECT_URL = '/' # Após login, redireciona para a página inicial

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", default=False, cast=bool)

# Configure ALLOWED_HOSTS from environment variable
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='').split(',')

# Configure CSRF trusted origins from environment variable
CSRF_TRUSTED_ORIGINS = config('CSRF_TRUSTED_ORIGINS', default='').split(',')

# Application definition

INSTALLED_APPS = [
    'church_app.apps.ChurchAppConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'storages',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'church_site.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'church_site.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

if os.environ.get("CI"):
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": os.path.join(BASE_DIR, "db.sqlite3"),
        }
    }

elif ENV == "production":
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": config("DB_NAME"),
            "USER": config("DB_USER"),
            "PASSWORD": config("DB_PASSWORD"),
            "HOST": config("DB_HOST"),
            "PORT": config("DB_PORT"),
        }
    }
else:
    # Local ou outros ambientes de teste
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": config("DB_NAME"),
            "USER": config("DB_USER"),
            "PASSWORD": config("DB_PASSWORD"),
            "HOST": config("DB_HOST", default="127.0.0.1"),
            "PORT": config("DB_PORT", default="5432"),
        }
    }

if ENV == "production":
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    USE_X_FORWARDED_HOST = True


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

#STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Supabase Storage (S3 compatível)
# AWS_ACCESS_KEY_ID = config("AWS_ACCESS_KEY_ID")
# AWS_SECRET_ACCESS_KEY = config("AWS_SECRET_ACCESS_KEY")
# AWS_STORAGE_BUCKET_NAME = config("AWS_STORAGE_BUCKET_NAME")
# AWS_S3_ENDPOINT_URL = config('AWS_S3_ENDPOINT_URL')
# PROJECT_REF = config('PROJECT_REF')
# AWS_QUERYSTRING_AUTH = False


# --- Configurações de Arquivos Estáticos (Essencial para collectstatic) ---

# 1. STATICFILES_DIRS (Opcional, se você tiver arquivos estáticos globais)
# Onde o Django busca arquivos estáticos em desenvolvimento, além dos 'static' dentro dos apps.
# STATICFILES_DIRS = [
#     os.path.join(BASE_DIR, 'static_dev'), 
# ]

# 2. STATIC_ROOT (Obrigatorio para collectstatic)
# Onde o 'collectstatic' reunirá os arquivos para, então, o STATICFILES_STORAGE enviá-los ao R2.
# Crie uma pasta 'staticfiles' na raiz do seu projeto (fora do escopo do Git)
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# 3. STATIC_URL (URL para acesso público - já deve estar configurado para o R2)
# STATIC_URL = 'https://<SEU_CUSTOM_DOMAIN_OU_R2_PUBLIC_URL>/static/'



# --- Configurações Cloudflare R2 (S3-Compatible) ---

# Importante: O R2 usa a API S3. Você usará as chaves e o endpoint do R2.

# 1. Credenciais do Cloudflare R2 (Geradas no painel R2)
# Recomenda-se carregar de variáveis de ambiente (.env)
AWS_ACCESS_KEY_ID = config("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = config("AWS_SECRET_ACCESS_KEY")

# 2. Nome do seu Bucket R2
AWS_STORAGE_BUCKET_NAME = config("AWS_STORAGE_BUCKET_NAME")

# 3. Endpoint do Cloudflare R2
# Formato: https://<SEU_ACCOUNT_ID>.r2.cloudflarestorage.com
AWS_S3_ENDPOINT_URL = f'https://{config("ACCOUNT_ID")}.r2.cloudflarestorage.com'

# 4. Versão da assinatura (necessário para R2)
AWS_S3_SIGNATURE_VERSION = 's3v4'

# 5. Configuração para Media Files (Uploads de Usuário - FileField/ImageField)
# Use o backend S3Boto3Storage para R2
#DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
AWS_S3_FILE_OVERWRITE = False # Não sobrescrever arquivos com o mesmo nome

# 6. (Opcional) Configuração para Static Files (CSS, JS, Imagens do Projeto)
# Se você quiser servir arquivos estáticos pelo R2 (muito comum em produção)
#STATICFILES_STORAGE = 'church_site.storage_backends.R2StaticStorage'
# URL base para os arquivos estáticos (pode ser o R2 public bucket URL ou um Cloudflare Custom Domain)
AWS_LOCATION = 'static'
#STATIC_URL = 'https://pub-ba1a1273b7274c32ada11ba5a4254e40.r2.dev/'

AWS_DEFAULT_ACL = 'public-read'

AWS_S3_SIGNATURE_VERSION = 's3v4'

# --- Configuração Moderna de Storages (Django 4.2+) ---

STATIC_URL = config('STATIC_URL')
IS_BUILD = os.environ.get("DJANGO_DOCKER_BUILD") == "1"

if IS_BUILD:
    STORAGES = {
        "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
        "staticfiles": {
            "BACKEND": "church_site.storage_backends_build.BuildStaticStorage"
        }
    }

STORAGES = {
    # 1. Configuração Padrão de Arquivos (Uploads de Usuário/Media)
    "default": {
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        "OPTIONS": {
            "bucket_name": AWS_STORAGE_BUCKET_NAME,
            "endpoint_url": AWS_S3_ENDPOINT_URL,
            "access_key": AWS_ACCESS_KEY_ID,
            "secret_key": AWS_SECRET_ACCESS_KEY,
            "location": "", # Opcional: define uma pasta 'media/' para uploads
            "default_acl": "public-read",
            "file_overwrite": False,
        }
    },
    
    # # 2. Configuração de Arquivos Estáticos (collectstatic)
    # # STATICFILES
    "staticfiles": {
        "BACKEND": "church_site.storage_backends.R2StaticStorage",
    },
}

# Email Backend - Durante o desenvolvimento, use o console backend
if ENV == "local":
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Configurações de E-mail para Produção
if ENV == "production":
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = 'smtp.gmail.com'
    EMAIL_PORT = 587
    EMAIL_USE_TLS = True
    EMAIL_HOST_USER = config('EMAIL_HOST_USER')
    EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')
    DEFAULT_FROM_EMAIL = config('EMAIL_HOST_USER')