# Generated by Django 5.2.6 on 2026-03-21 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Aceite'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Indica se o usuário já saiu da lista de espera.', verbose_name='Aprovado'),
        ),
    ]
