# Generated by Django 5.2.6 on 2026-03-21 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('church_app', '0002_user_accepted_at_user_is_approved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_hide_post', 'Pode ocultar postagens impróprias'), ('can_delete_comment', 'Pode excluir comentários ofensivos'), ('can_approve_waitlist', 'Pode aprovar novos irmãos na lista de espera'), ('can_create_reading_plan', 'Pode criar e publicar planos de leitura oficiais'), ('can_edit_reading_plan', 'Pode editar planos de leitura existentes'), ('can_mute_user', 'Pode silenciar usuários por tempo determinado'), ('can_report_review', 'Pode analisar denúncias de usuários')]},
        ),
    ]
