# Generated by Django 5.2.6 on 2026-01-23 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_app', '0002_book_chapter_verse'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlanTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveIntegerField()),
                ('day_number', models.PositiveIntegerField()),
                ('chapters', models.ManyToManyField(related_name='plan_tasks', to='church_app.chapter')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='church_app.readingplan')),
            ],
            options={
                'ordering': ['week_number', 'day_number'],
                'unique_together': {('plan', 'week_number', 'day_number')},
            },
        ),
    ]
