# Generated by Django 5.2.6 on 2026-01-23 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('church_app', '0003_readingplan_plantask'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='plantask',
            unique_together=set(),
        ),
    ]
