# Generated by Django 5.2.6 on 2026-03-22 02:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_app', '0003_alter_user_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text="Ex: 'Aprovou usuário', 'Ocultou postagem'", max_length=255)),
                ('target_id', models.PositiveIntegerField(blank=True, help_text='ID primário do objeto que sofreu a ação.', null=True)),
                ('target_type', models.CharField(blank=True, help_text="Nome do modelo de destino (ex: 'User', 'Post').", max_length=100, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(help_text='Usuário responsável pela ação.', on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Atividade',
                'verbose_name_plural': 'Logs de Atividades',
                'ordering': ['-timestamp'],
            },
        ),
    ]
