# Generated by Django 5.2.6 on 2026-03-22 05:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_app', '0004_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingplan',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='readingplan',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='readingplan',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
