# Generated by Django 5.2.6 on 2026-03-22 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_app', '0006_alter_post_options_post_content_type_post_object_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingplan',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
