# Generated by Django 5.2.6 on 2026-03-22 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('church_app', '0008_comment_deleted_at_post_deleted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readingplan',
            name='draft',
        ),
    ]
