# Generated by Django 5.2.6 on 2026-05-08 20:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_app', '0009_remove_readingplan_draft'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plantask',
            options={'ordering': ['scheduled_date']},
        ),
        migrations.RemoveField(
            model_name='plantask',
            name='day_number',
        ),
        migrations.RemoveField(
            model_name='plantask',
            name='week_number',
        ),
        migrations.AddField(
            model_name='plantask',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plantask',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_tasks', to='church_app.archive'),
        ),
        migrations.AddField(
            model_name='plantask',
            name='scheduled_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
