# Generated by Django 5.2.6 on 2026-05-08 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_app', '0010_alter_plantask_options_remove_plantask_day_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantask',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
