# Generated by Django 5.2.6 on 2026-05-09 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_app', '0011_alter_plantask_scheduled_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantask',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='plan_tasks/%Y/%m/'),
        ),
    ]
